#!/usr/bin/env bash
# Example usage:
# set status_format="mutt_xtitle 'xterm titlebar fmt' 'mutt status fmt'|"

DATA="$2"
if [ -z "$DATA" ]; then
	DATA="$1"
fi

case "${TERM}" in
xterm*)
	# Set the xterm title
	echo -en "\033]0;${DATA}\007" > /dev/tty
	;;
screen*)
	# Set the screen title
	echo -en "\033k${DATA}\033\\" >/dev/tty
	;;
esac

# Return the string unchanged
echo "$1"
