#!/usr/bin/env bash
# Example usage:
# set status_format="mutt_xtitle 'xterm titlebar fmt' 'mutt status fmt'|"

# Set the xterm title
case "${TERM}" in
xterm*|rxvt*|screen*)
	echo -ne "\033]0;$1\007" > /dev/tty
	;;
esac

# Return the string unchanged
echo "$2"

