#! bash

# This file sets up the environment correctly. It gets run for every shell,
# so it must be fast. Also, starting a shell within a shell shouldn't change
# the environment. The path manipulation functions are useful for this.

# Files will be created by default rwx user only
umask 0077

# General environment settings
export PAGER="less"
export EDITOR="vim"
export CVS_RSH="ssh"
export RSYNC_RSH="ssh"
export PYTHONSTARTUP="${HOME}/.pythonrc.py"
export HISTCONTROL="ignoredups"
export HISTSIZE="10000"

# Load the bash functions
source "${HOME}/.bash/functions"

# The current directory shouldn't be in the path
pathremove .

# I am an admin kinda person... thus I like having access to sbin
pathappend "/sbin"
pathappend "/usr/sbin"

# ~/bin should be in the front of path if it exists
pathprepend "${HOME}/bin"

# Load local environment settings
ssource "${HOME}/.bash/environment_local"

