#! bash
# vim:set nolist noet tw=0 ts=4 sw=4 sts=4:

# Sets up the shell for interactive commands

# Use the terminfo backspace character as the erase character. This is not
# enabled by default because terminfo is often broken.
#stty erase $(tput kbs)

# Prompt: user@host:(chroot)directory$
PS1='\u@\h:'"${debian_chroot:+($debian_chroot)}"'\w\n\$ '

# Check for unsupported TERM variable
if ! tput init &> /dev/null; then
	echo "Warning! TERM=$TERM unsupported, using TERM=xterm"
	export TERM=xterm
fi

# The all important colours!
ssource "${HOME}/.bash/colors"

# xterm titlebar displays 'hostname:workingdir'
if (tput hs || tput tsl) &> /dev/null; then
	PROMPT_COMMAND='tput tsl; echo -n "${HOSTNAME/.*}:${PWD/$HOME/~}"; tput fsl;'
fi

PROMPT_COMMAND='GIT_BRANCH="$(git_branch_name)";'

# screen window displays current command
case "${TERM}" in
screen*)
	PROMPT_COMMAND="$PROMPT_COMMAND echo -ne '\033k\033\\';"
	;;
esac

# Useful aliases
alias ls='ls --color=auto'
alias ll='ls -hlF'
alias la='ls -ha'
alias  l='ls -halF'
alias ld='ls -ld'
alias f='find . -iname'
alias webshare='python2 -c "import SimpleHTTPServer; SimpleHTTPServer.test()"'
alias rm='rm -i'
alias less='less -R'
alias grep='grep --color=auto --exclude "*.svn-base"'

# Bash should check the terminal size after every command terminates
shopt -s checkwinsize
# Don't attempt to tab-complete an empty line
shopt -s no_empty_cmd_completion

mkdir -p "/tmp/$USER/ssh"

# Local customisations
ssource "${HOME}/.bash/interactive_local"

# Load bash completion if available
ssource "/etc/bash_completion"

[[ -z "$_DISABLE_GIT_CHECK" ]] && _git_show_changed_files "$(readlink ~/.bash)/.."
