#! bash

# Sets up the shell for interactive commands

# Use the terminfo backspace character as the erase character. This is not
# enabled by default because terminfo is often broken.
#stty erase $(tput kbs)

# Prompt: user@host:directory$
PS1='\u@\h:\w\$ '

# The all important colours!
ssource "${HOME}/.bash/colors"

# xterm titlebar displays current command
case "${TERM}" in
xterm*|rxvt*)
	HOSTNAME="$(hostname | cut -d '.' -f 1)"
	CWD_WITHHOME='"$(echo "${PWD}" | sed "s|^${HOME}|~|")"'
	PROMPT_COMMAND="echo -ne \"\033]0;${HOSTNAME}: ${CWD_WITHHOME}\007\""
	unset HOSTNAME
	;;
screen*)
	PS1="\[\033k\033\\\\\]${PS1}"
	;;
*)
	;;
esac

# Useful aliases
alias ls='ls --color=auto'
alias ll='ls -hlF'
alias la='ls -ha'
alias  l='ls -halF'
alias rm='rm -i'
alias less='less -R'

# Bash should check the terminal size after every command terminates
shopt -s checkwinsize

# Local customisations
ssource "${HOME}/.bash/interactive_local"

