#! bash

# Is run whenever we have a login interactive shell. Just prints a little
# welcome message.

echo "Welcome to $(uname)"
if which fortune &> /dev/null; then
	echo $(fortune -s)
	echo
fi

ssource "${HOME}/.bash/login_local"

